<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24760" started-at="2018-04-26T12:08:09Z" finished-at="2018-04-26T12:08:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="24760" started-at="2018-04-26T12:08:09Z" finished-at="2018-04-26T12:08:34Z">
      <class name="testng.BrokenImagesTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testng.BrokenImagesTest@5ce81285]" name="beforeTest" is-config="true" duration-ms="10342" started-at="2018-04-26T12:08:10Z" finished-at="2018-04-26T12:08:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="verifyBrokenImagaes()[pri:0, instance:testng.BrokenImagesTest@5ce81285]" name="verifyBrokenImagaes" duration-ms="13445" started-at="2018-04-26T12:08:20Z" finished-at="2018-04-26T12:08:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Found broken images expected [0] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Found broken images expected [0] but found [2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at testng.BrokenImagesTest.verifyBrokenImagaes(BrokenImagesTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBrokenImagaes -->
        <test-method status="PASS" signature="kill()[pri:0, instance:testng.BrokenImagesTest@5ce81285]" name="kill" is-config="true" duration-ms="953" started-at="2018-04-26T12:08:33Z" finished-at="2018-04-26T12:08:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kill -->
      </class> <!-- testng.BrokenImagesTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
